service: examples

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    env:
      ENV_EXAMPLE: ${env:env-example}
      PARAMETER_EXAMPLE: ${param:param-example}
