name: Serverless Deploy

on:
  push:
    branches:
      - main

jobs:
  Serverless-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 

      - name: Serverless Deploy
        uses: dhollerbach/actions.serverless-with-python-requirements@develop
        with:
          canary-deployments: false
          domain-manager: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STAGE: dev
